Remove .ghc.environment* files from .gitignore.
We need to know if these ghc environment files exist, as they can break
nix builds. These files are auto-generated by
`cabal new-build/new-configure`. The file represents all the packages
that cabal has figured out it will use. But these packages differ than
the ones specified via nix (specifically, the package versions in the
nix channels). This causes the build to break, because I suppose nix is
running `ghc` or `ghci`, and these will attempt to load packages
specified in the env file.

So the solution is to (1) not `cabal new-build` and (2) delete these
.ghc.environment* files if you do use `new-build`.

Error you'll see:

/nix/store/4mdp8nhyfddh7bllbi7xszz7k9955n79-Setup.hs:1:1: error:
    Could not load module ‘Distribution.Simple’
    It is a member of the hidden package ‘Cabal-2.4.0.1’.
    You can run ‘:set -package Cabal’ to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v to see a list of the files searched for.
  |
1 | import Distribution.Simple
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^
builder for '/nix/store/ybg658ybq9whx2fhd6pbsgw4b58m6dv9-elbenshiracom-0.1.0.0.drv' failed with exit code 1
error: build of '/nix/store/ybg658ybq9whx2fhd6pbsgw4b58m6dv9-elbenshiracom-0.1.0.0.drv' failed